version: '2'
services:
  mysql:
    image: mysql:latest
    volumes:
      - "./data/db:/var/lib/mysql"
      - "./config/mysql/:/etc/mysql/conf.d/"
    restart: unless-stopped
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME}
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
  memcached:
    image: memcached:latest
    restart: unless-stopped
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    restart: unless-stopped
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
    expose:
      - 9200
    volumes:
      - "./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "./config/elasticsearch/plugins:/usr/share/elasticsearch/plugins"
  phpfpm:
    image: 10up/phpfpm
    depends_on:
      - mysql
      - memcached
      - elasticsearch
    volumes:
      - "./wordpress:/var/www/html"
      - "./config/php-fpm/php.ini:/usr/local/etc/php/php.ini"
      - "./config/php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
    restart: unless-stopped
    links:
      - mysql
  nginx:
    depends_on:
      - phpfpm
    image: nginx:latest
    volumes:
      - "./wordpress:/var/www/html"
      - "./config/nginx/:/etc/nginx/conf.d/"
    links:
      - phpmyadmin
    restart: unless-stopped
  phpmyadmin:
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME}
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    expose:
      - 80
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
